[2021-07-08 13:23:51,984] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:23:37.351131+00:00 [queued]>
[2021-07-08 13:23:52,004] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:23:37.351131+00:00 [queued]>
[2021-07-08 13:23:52,005] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 13:23:52,005] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-08 13:23:52,005] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 13:23:52,014] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): upload_to_GCS> on 2021-07-08T13:23:37.351131+00:00
[2021-07-08 13:23:52,020] {standard_task_runner.py:52} INFO - Started process 18542 to run task
[2021-07-08 13:23:52,027] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'upload_to_GCS', '2021-07-08T13:23:37.351131+00:00', '--job-id', '132', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmpvs3xsila', '--error-file', '/tmp/tmp3csoxw9_']
[2021-07-08 13:23:52,034] {standard_task_runner.py:77} INFO - Job 132: Subtask upload_to_GCS
[2021-07-08 13:23:52,089] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:23:37.351131+00:00 [running]> on host 3cf0296804bd
[2021-07-08 13:23:52,152] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=upload_to_GCS
AIRFLOW_CTX_EXECUTION_DATE=2021-07-08T13:23:37.351131+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-08T13:23:37.351131+00:00
[2021-07-08 13:23:52,154] {logging_mixin.py:104} INFO - exam-de-natchanon
[2021-07-08 13:23:52,155] {logging_mixin.py:104} INFO - gs://bluepi-landing-bucket
[2021-07-08 13:23:52,165] {logging_mixin.py:104} INFO - exam-de-natchanon
[2021-07-08 13:23:52,166] {logging_mixin.py:104} INFO - bluepi-landing-bucket
[2021-07-08 13:23:52,167] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bluepi_dag.py", line 54, in _upload_to_gcs
    blob.upload_from_filename(source_file_name)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2628, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/*.csv'
[2021-07-08 13:23:52,170] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=bluepi_dag, task_id=upload_to_GCS, execution_date=20210708T132337, start_date=20210708T132351, end_date=20210708T132352
[2021-07-08 13:23:52,201] {local_task_job.py:151} INFO - Task exited with return code 1
