[2021-07-08 13:22:37,185] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:22:23.348968+00:00 [queued]>
[2021-07-08 13:22:37,204] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:22:23.348968+00:00 [queued]>
[2021-07-08 13:22:37,205] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 13:22:37,205] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-08 13:22:37,206] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 13:22:37,215] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): upload_to_GCS> on 2021-07-08T13:22:23.348968+00:00
[2021-07-08 13:22:37,221] {standard_task_runner.py:52} INFO - Started process 18436 to run task
[2021-07-08 13:22:37,226] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'upload_to_GCS', '2021-07-08T13:22:23.348968+00:00', '--job-id', '123', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmppgndll25', '--error-file', '/tmp/tmpt9mc7c39']
[2021-07-08 13:22:37,233] {standard_task_runner.py:77} INFO - Job 123: Subtask upload_to_GCS
[2021-07-08 13:22:37,281] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:22:23.348968+00:00 [running]> on host 3cf0296804bd
[2021-07-08 13:22:37,340] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=upload_to_GCS
AIRFLOW_CTX_EXECUTION_DATE=2021-07-08T13:22:23.348968+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-08T13:22:23.348968+00:00
[2021-07-08 13:22:37,342] {logging_mixin.py:104} INFO - exam-de-natchanon
[2021-07-08 13:22:37,342] {logging_mixin.py:104} INFO - gs://bluepi-landing-bucket
[2021-07-08 13:22:37,353] {logging_mixin.py:104} INFO - bluepi-landing-bucket
[2021-07-08 13:22:37,355] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bluepi_dag.py", line 53, in _upload_to_gcs
    blob.upload_from_filename(source_file_name)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2628, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/*.csv'
[2021-07-08 13:22:37,358] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=bluepi_dag, task_id=upload_to_GCS, execution_date=20210708T132223, start_date=20210708T132237, end_date=20210708T132237
[2021-07-08 13:22:37,398] {local_task_job.py:151} INFO - Task exited with return code 1
