[2021-07-08 12:22:52,694] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T12:22:36.089569+00:00 [queued]>
[2021-07-08 12:22:52,719] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T12:22:36.089569+00:00 [queued]>
[2021-07-08 12:22:52,720] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 12:22:52,720] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-08 12:22:52,720] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 12:22:52,730] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): upload_to_GCS> on 2021-07-08T12:22:36.089569+00:00
[2021-07-08 12:22:52,737] {standard_task_runner.py:52} INFO - Started process 14533 to run task
[2021-07-08 12:22:52,744] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'upload_to_GCS', '2021-07-08T12:22:36.089569+00:00', '--job-id', '105', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmpshxppe5c', '--error-file', '/tmp/tmp5_nufodo']
[2021-07-08 12:22:52,751] {standard_task_runner.py:77} INFO - Job 105: Subtask upload_to_GCS
[2021-07-08 12:22:52,807] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T12:22:36.089569+00:00 [running]> on host 3cf0296804bd
[2021-07-08 12:22:52,864] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=upload_to_GCS
AIRFLOW_CTX_EXECUTION_DATE=2021-07-08T12:22:36.089569+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-08T12:22:36.089569+00:00
[2021-07-08 12:22:52,866] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-08 12:22:52,868] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'gsutil cp /opt/***/dags/*.csv gs://bluepi-landing-bucket']
[2021-07-08 12:22:52,878] {subprocess.py:75} INFO - Output:
[2021-07-08 12:22:52,881] {subprocess.py:79} INFO - bash: gsutil: command not found
[2021-07-08 12:22:52,882] {subprocess.py:83} INFO - Command exited with return code 127
[2021-07-08 12:22:52,894] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-08 12:22:52,897] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=bluepi_dag, task_id=upload_to_GCS, execution_date=20210708T122236, start_date=20210708T122252, end_date=20210708T122252
[2021-07-08 12:22:52,955] {local_task_job.py:151} INFO - Task exited with return code 1
