[2021-07-08 13:25:23,906] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:25:11.159993+00:00 [queued]>
[2021-07-08 13:25:23,925] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:25:11.159993+00:00 [queued]>
[2021-07-08 13:25:23,926] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 13:25:23,927] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-08 13:25:23,927] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 13:25:23,936] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): upload_to_GCS> on 2021-07-08T13:25:11.159993+00:00
[2021-07-08 13:25:23,941] {standard_task_runner.py:52} INFO - Started process 18665 to run task
[2021-07-08 13:25:23,946] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'upload_to_GCS', '2021-07-08T13:25:11.159993+00:00', '--job-id', '141', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmpspku1bml', '--error-file', '/tmp/tmpg04b23gh']
[2021-07-08 13:25:23,952] {standard_task_runner.py:77} INFO - Job 141: Subtask upload_to_GCS
[2021-07-08 13:25:24,001] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.upload_to_GCS 2021-07-08T13:25:11.159993+00:00 [running]> on host 3cf0296804bd
[2021-07-08 13:25:24,062] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=upload_to_GCS
AIRFLOW_CTX_EXECUTION_DATE=2021-07-08T13:25:11.159993+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-08T13:25:11.159993+00:00
[2021-07-08 13:25:24,064] {logging_mixin.py:104} INFO - exam-de-natchanon
[2021-07-08 13:25:24,065] {logging_mixin.py:104} INFO - gs://bluepi-landing-bucket
[2021-07-08 13:25:24,065] {logging_mixin.py:104} INFO - /opt/***/dags/user.csv
[2021-07-08 13:25:24,077] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bluepi_dag.py", line 53, in _upload_to_gcs
    blob.upload_from_filename(source_file_name)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2628, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/user.csv'
[2021-07-08 13:25:24,080] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=bluepi_dag, task_id=upload_to_GCS, execution_date=20210708T132511, start_date=20210708T132523, end_date=20210708T132524
[2021-07-08 13:25:24,117] {local_task_job.py:151} INFO - Task exited with return code 1
