[2021-07-08 11:33:03,310] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_users_data 2021-07-08T11:32:57.634553+00:00 [queued]>
[2021-07-08 11:33:03,332] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bluepi_dag.upload_users_data 2021-07-08T11:32:57.634553+00:00 [queued]>
[2021-07-08 11:33:03,333] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 11:33:03,333] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-08 11:33:03,333] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-08 11:33:03,342] {taskinstance.py:1107} INFO - Executing <Task(PostgresToGCSOperator): upload_users_data> on 2021-07-08T11:32:57.634553+00:00
[2021-07-08 11:33:03,348] {standard_task_runner.py:52} INFO - Started process 11151 to run task
[2021-07-08 11:33:03,355] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bluepi_dag', 'upload_users_data', '2021-07-08T11:32:57.634553+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bluepi_dag.py', '--cfg-path', '/tmp/tmpnvny73kj', '--error-file', '/tmp/tmpi7s53lah']
[2021-07-08 11:33:03,359] {standard_task_runner.py:77} INFO - Job 43: Subtask upload_users_data
[2021-07-08 11:33:03,414] {logging_mixin.py:104} INFO - Running <TaskInstance: bluepi_dag.upload_users_data 2021-07-08T11:32:57.634553+00:00 [running]> on host 3cf0296804bd
[2021-07-08 11:33:03,489] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=natchanon
AIRFLOW_CTX_DAG_ID=bluepi_dag
AIRFLOW_CTX_TASK_ID=upload_users_data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-08T11:32:57.634553+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-08T11:32:57.634553+00:00
[2021-07-08 11:33:03,491] {sql_to_gcs.py:150} INFO - Executing query
[2021-07-08 11:33:03,502] {base.py:78} INFO - Using connection to: id: my_postgres_conn. Host: 35.247.174.171, Port: 5432, Schema: postgres, Login: exam, Password: ***, extra: {}
[2021-07-08 11:33:05,043] {sql_to_gcs.py:153} INFO - Writing local data files
[2021-07-08 11:33:05,043] {sql_to_gcs.py:202} INFO - Current file count: 1
[2021-07-08 11:33:05,045] {sql_to_gcs.py:164} INFO - Uploading 1 files to GCS.
[2021-07-08 11:33:05,066] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 165, in execute
    self._upload_to_gcs(files_to_upload)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 369, in _upload_to_gcs
    gzip=self.gzip if tmp_file.get('file_name') != self.schema_filename else False,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 460, in upload
    bucket = client.bucket(bucket_name)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/client.py", line 298, in bucket
    return Bucket(client=self, name=bucket_name, user_project=user_project)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/bucket.py", line 581, in __init__
    name = _validate_name(name)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/_helpers.py", line 74, in _validate_name
    raise ValueError("Bucket names must start and end with a number or letter.")
ValueError: Bucket names must start and end with a number or letter.
[2021-07-08 11:33:05,069] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=bluepi_dag, task_id=upload_users_data, execution_date=20210708T113257, start_date=20210708T113303, end_date=20210708T113305
[2021-07-08 11:33:05,102] {local_task_job.py:151} INFO - Task exited with return code 1
